### PR TITLE
Example of problem with recyclerview skeletons not reappearing correctly

### PR DESCRIPTION
**Pull request by mortenholmgaard**
Here is an example of my skeleton problems in a recycler view. 
The case is that the skeletons appear correctly at first but when recycled they does not allways appear.
I have added a video of the case here: https://verticacloud-my.sharepoint.com/:v:/g/personal/mho_vertica_dk/EUkhCIRKtgxGjYcqOGy2zVEBJGpqZaG82_mTMgg6BLuBog?e=cgTAht (I will be removed after 7 days so let me know if I should reshare the file - company policy)
Note that after the video i have changed the code a bit to return different image for even and odd levels to make it simplere to see the problem.

Related to issue: https://github.com/EudyContreras/Skeleton-Bones/issues/20

### CODE REVIEW

**Comment by EudyContreras** [comment]
I will now be inspecting the code and attempt to address the highlighted issues. I will get back to you with my findings and progress 🙏

**Comment by EudyContreras** [comment]
@mortenholmgaard could you repost the video please?

**Comment by mortenholmgaard** [comment]
The link is same but I could extend the expiry a week @EudyContreras : https://verticacloud-my.sharepoint.com/:v:/g/personal/mho_vertica_dk/EUkhCIRKtgxGjYcqOGy2zVEBJGpqZaG82_mTMgg6BLuBog?e=FzuhuZ

**Comment by EudyContreras** [comment]
@mortenholmgaard I have looked through your example and I have a few questions. I see some things that are a bit confusing. Do you think it would be possible for us to have a call where you can in more detail explain the issue and your approach ?

**Comment by mortenholmgaard** [comment]
@EudyContreras Yeah we can have a call on Teams or call me on +4528573576.

**Comment by mortenholmgaard** [comment]
To be clear on what I am looking for you might be able to let me know of a better solution than the one I came up with:
- Different subviews could stop showing skeletons on different times (different data endpoints for e.g. prices and inventory)
- Possible to show one skeleton for the areal of a ViewGroup, as sometimes there are multiple small subviews to make the ui show as  wanted, but it will look awfull if skeletons where shown on all of them, and not just the parent.
- Recycle the ViewHolder with skeletons and show -> hide them again, currently it does not seem to always work as show in the example here.

Thoughts:
- Is there a default skeleton/bone (the difference is no that clear to me) as it seems you need to ignoreBones to not be shown, though they are not configured? So to me there should either be a default styling possible or no need to ignore bones as they should be explicit configured to be shown.
- To me skeletons should be bond to views individually, and then on viewGroups skeletons could be added as it was a view or trigger all skeletons configured subviews. And it might be almost exactly so it is but it is just not clear to me :)

**Comment by EudyContreras** [comment]
> To be clear on what I am looking for you might be able to let me know of a better solution than the one I came up with:
> 
> * Different subviews could stop showing skeletons on different times (different data endpoints for e.g. prices and inventory)
> * Possible to show one skeleton for the areal of a ViewGroup, as sometimes there are multiple small subviews to make the ui show as  wanted, but it will look awfull if skeletons where shown on all of them, and not just the parent.
> * Recycle the ViewHolder with skeletons and show -> hide them again, currently it does not seem to always work as show in the example here.

Well at the moment the way it was design was more like this. Imagine we have a pice of data such as

```kotlin
data class User(
  val name: String,
  val age: int,
  val profileImageUrl: String,
  val occupation: Occupation
)
```
We can can then attach a skeleton to the view showing this data and let the image be the skeleton owner or not since it will load independently. I want to provide more flexibility and this is subject to change.

> * Is there a default skeleton/bone (the difference is no that clear to me) as it seems you need to ignoreBones to not be shown, though they are not configured? So to me there should either be a default styling possible or no need to ignore bones as they should be explicit configured to be shown.

This is a good concept. I can maybe add this as a setting 🙌 

> * To me skeletons should be bond to views individually, and then on viewGroups skeletons could be added as it was a view or trigger all skeletons configured subviews. And it might be almost exactly so it is but it is just not clear to me :)

Well the decision regarding this was the following. 
  * One drawable for (ViewGroup) skeleton with multiple bones (views). 
  * It is possible to control when the bones within a skeleton will be loaded and stop showing the skeleton animations

I really have to improve the docs and make it clearer.  I have not had any time to invest on the project as of lately. I am extremely busy and barely have time after work. Im in desperate need of contributions 😅. 
I have not abandoned this project I just haven't had time 😞

**Pull request merged**
